@baseUrl = http://localhost:3555
@gateway = https://api-gateway-ashy-seven.vercel.app
@consumerId = a29d457a-e8b1-4999-8bc1-11ed925254fc

### Criar Indicação (Novo Consumidor na Rede de Cashback)
POST {{baseUrl}}/indicacao
Content-Type: application/json

{
  "id": "4df5b96b-b692-4552-a919-fdaad400567c",
  "username": "Redecity Inova Simples",
  "nickname": "@redecity",
  "full_name": "Redecity Inova Simples",
  "referral_id": "67be4156-dee8-4c36-a205-61756c77c926"
}


###
POST {{baseUrl}}/indicacao
Content-Type: application/json

{
  "id": "{{consumerId}}",
  "username": "RedeCity", 
  "nickname": "@redecity", 
  "full_name": "Rede City",
  "referral_id": "67be4156-dee8-4c36-a205-61756c77c926"
}

### Ativar Consumidor na Rede de Cashback
PATCH {{baseUrl}}/indicacao/{{consumerId}}/activate
Accept: application/json

### Obter Indicados (Nível 1 e Nível 2) — Local
GET {{baseUrl}}/indicacao/{{consumerId}}/indicados
Accept: application/json

### Obter Indicados (Nível 1 e Nível 2) — Via API Gateway (produção)
GET {{gateway}}/api/cashback/indicacao/{{consumerId}}/indicados
Accept: application/json



