@baseUrl = http://localhost:3555
@gateway = https://api-gateway-ashy-seven.vercel.app
@consumerId = 67be4156-dee8-4c36-a205-61756c77c926

### Criar Indicação (Novo Consumidor na Rede de Cashback)
POST {{baseUrl}}/indicacao
Content-Type: application/json

{
  "id": "{{consumerId}}",
  "username": "@redecity",
  "full_name": "Rede City",
  "referralCodeUsed": "@savastane"
}

### Ativar Consumidor na Rede de Cashback
PATCH {{baseUrl}}/indicacao/{{consumerId}}/activate
Accept: application/json

### Obter Indicados (Nível 1 e Nível 2) — Local
GET {{baseUrl}}/indicacao/{{consumerId}}/indicados
Accept: application/json

### Obter Indicados (Nível 1 e Nível 2) — Via API Gateway (produção)
GET {{gateway}}/api/cashback/indicacao/{{consumerId}}/indicados
Accept: application/json



